import Head from "next/head";
import HeaderImage from "../components/sections/HeaderImage";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        <HeaderImage />
      </div>
    </div>
  );
}

export const getServerSideProps = async (ctx) => {
  return {
    props: {
      data: null,
    },
  };
};
