import Head from "next/head";
import HeaderImage from "../../sections/HeaderImage";
import VideoContainer from "./VideoContainer";

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Paartly | Vehicle Modifications</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VideoContainer />
    </>
  );
}
