import Head from "next/head";
import Image from "next/image";
import HeaderImage from "../../sections/HeaderImage";

export default function HomePage() {
  return (
    <>
      <Head>
        <title>modlista | vehicle modifications</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>{" "}
      <section className="pb-16 md:pb-6">
        <div className="items-center justify-center hidden w-full py-24 md:flex">
          <h2 className="mx-auto text-4xl font-bold text-center text-white md:text-5xl group">
            Your{" "}
            <span className="italic font-light underline text-ag-yellow group-hover:text-ag-green">
              mods
            </span>{" "}
            in one place.
          </h2>
        </div>
        <HeaderImage />
      </section>
    </>
  );
}
