import Head from "next/head";
import Image from "next/image";
import HeaderImage from "../../sections/HeaderImage";

export default function HomePage() {
  return (
    <>
      <Head>
        <title>modlista | vehicle modifications</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>{" "}
      <HeaderImage />
    </>
  );
}
